import matplotlib.pyplot as plt

# Function to generate random numbers


def linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums):
    # Initialize the seed state
    randomNums[0] = Xo

    # Generate the required numbers of random numbers
    for i in range(1, noOfRandomNums):
        # Follow the linear congruential method
        randomNums[i] = ((randomNums[i - 1] * a) + c) % m


# Driver Code
if __name__ == '__main__':
    # Seed value
    Xo = 5

    # Modulus parameter
    m = 7

    # Multiplier term
    a = 3

    # Increment term
    c = 3

    # Number of random numbers to be generated
    noOfRandomNums = 10

    # To store random numbers
    randomNums = [0] * noOfRandomNums

    # Generate random numbers
    linearCongruentialMethod(Xo, m, a, c, randomNums, noOfRandomNums)

    # Print the generated random numbers
    print("Generated random numbers:", randomNums)

    # Plot the generated random numbers
    plt.figure(figsize=(10, 6))
    plt.plot(randomNums, marker='o', color='blue',
             linestyle='-', linewidth=1, markersize=6)
    plt.title("Random Numbers Generated by Linear Congruential Method")
    plt.xlabel("Iteration")
    plt.ylabel("Random Number")
    plt.grid(True)
    plt.show()
